apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service          # ✅ changed
  namespace: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service       # ✅ changed
  template:
    metadata:
      labels:
        app: product-service     # ✅ changed
    spec:
      containers:
      - name: product            # ✅ optional but good
        image: sanj231123/product-service:v3   # ✅ changed
        ports:
        - containerPort: 8083
        resources:

          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
  
