apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-istio
  namespace: ecom
spec:
  podSelector: {} # Applies to all pods in the namespace
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # 1. Allow ALL traffic coming from inside the same namespace (App-to-App traffic)
    - from:
        - podSelector: {}

    # 2. Allow traffic from Istio Ingress Gateway
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system

    # 3. Allow Kubelet Health Probes (Liveness/Readiness) and Istio control ports
    - ports:
        - protocol: TCP
          port: 15001 # Istio outbound proxy
        - protocol: TCP
          port: 15006 # Istio inbound proxy
        - protocol: TCP
          port: 15021 # Istio health check port (Crucial!)

  egress:
    # 1. Allow application pods to talk to each other inside the namespace
    - to:
        - podSelector: {}

    # 2. Allow Istio sidecars to talk to Istio Control Plane (istiod)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 15012
        - protocol: TCP
          port: 15017
