apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ecom

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management

        ports:
        - containerPort: 5672
        - containerPort: 15672

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
