grafana:
  adminPassword: admin123

  service:
    type: NodePort
    nodePort: 32000

prometheus:
  service:
    type: NodePort
    nodePort: 32001
  prometheusSpec:
    podMetadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"

alertmanager:
  enabled: true

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true
  prometheus:
    monitor:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"

prometheusOperator:
  deploymentAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
