apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: sanj231123/api-gateway:v16  # 🔥 change this
        ports:
        - containerPort: 8080
        resources:

          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
  
