apiVersion: v1
kind: Service

metadata:
  name: auth-service
  namespace: ecom
  labels:
    app: auth-service

spec:
  selector:
    app: auth-service

  ports:
    - name: http
      port: 8081
      targetPort: 8081

