apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service
  namespace: ecom

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service
        version: v1  

    spec:
      containers:

      - name: notification-service
        image: sanj231123/notification-service:v10
        imagePullPolicy: Always

        ports:
        - containerPort: 5008
        livenessProbe:
          httpGet:
            path: /health
            port: 5008
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 5008
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3  

        env:

        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:5672"

        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: EMAIL_USER

        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: EMAIL_PASS
