apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: ecom

  labels:
    app: notification-service

spec:

  selector:
    app: notification-service

  ports:
  - name: http
    port: 5008
    targetPort: 5008

  type: ClusterIP
