apiVersion: batch/v1
kind: CronJob

metadata:
  name: etcd-backup
  namespace: kube-system

spec:
  schedule: "0 */2 * * *"

  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2

  jobTemplate:
    spec:
      template:

        metadata:
          annotations:
            sidecar.istio.io/inject: "false"

        spec:

          hostNetwork: true
          restartPolicy: OnFailure

          nodeSelector:
            node-role.kubernetes.io/control-plane: ""

          containers:
          - name: etcd-backup

            image: bitnami/etcd:latest

            env:
            - name: ETCDCTL_API
              value: "3"

            command:
            - /bin/sh
            - -c
            - |
              TIMESTAMP=$(date +%d%m%Y_%H%M)

              etcdctl \
              --endpoints=https://127.0.0.1:2379 \
              --cacert=/etc/kubernetes/pki/etcd/ca.crt \
              --cert=/etc/kubernetes/pki/etcd/server.crt \
              --key=/etc/kubernetes/pki/etcd/server.key \
              snapshot save /backup/etcd/snapshot_${TIMESTAMP}.db

            volumeMounts:
            - name: etcd-certs
              mountPath: /etc/kubernetes/pki/etcd
              readOnly: true

            - name: backup-storage
              mountPath: /backup/etcd

            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"

              limits:
                cpu: "300m"
                memory: "256Mi"

          volumes:
          - name: etcd-certs
            hostPath:
              path: /etc/kubernetes/pki/etcd

          - name: backup-storage
            hostPath:
              path: /backup/etcd
