apiVersion: batch/v1
kind: CronJob

metadata:
  name: unpaid-order-cleanup
  namespace: ecom

spec:
  schedule: "*/5 * * * *"

  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2

  jobTemplate:
    spec:
      template:

        metadata:
          annotations:
            sidecar.istio.io/inject: "false"

        spec:

          restartPolicy: OnFailure

          containers:
          - name: cleanup
            image: mysql:8

            env:
            - name: MYSQL_PWD
              value: root123

            command:
            - /bin/sh
            - -c
            - |
              mysql -h mysql -uroot ecommerce -e "
              UPDATE orders
              SET status='CANCELLED'
              WHERE payment_status='PENDING'
              AND status='PLACED';
              "

            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"

              limits:
                cpu: "300m"
                memory: "256Mi"
